# Generated by Django 4.2.4 on 2023-08-20 21:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_blog', '0002_remove_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
    ]
